apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: homehello
  name: homehello
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homehello
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/homehello-default: "true"
        io.kompose.service: homehello
    spec:
      containers:
        - image: methi45docker/homehello
          name: homehello
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
